all: FisheryOverIPv6

CONTIKI=../../..

#CONTIKI_SOURCEFILES +=$(CONTIKI)/platform/cc2538dk/dev/DHT11.c
CONTIKI_TARGET_SOURCEFILES += DHT11-arch.c
CONTIKI_TARGET_SOURCEFILES += ds18b20-arch.c
include $(CONTIKI)/Makefile.include
